### ISSUE TITLE
Add 'tags' to Templates

### ISSUE THREAD

**Issue by donovanmuller** [donovanmuller/spring-cloud-dataflow-server-openshift#13]
Use the new category tags for OpenShift templates to categorise the Data Flow templates.

See https://docs.openshift.org/latest/dev_guide/templates.html#writing-description

**Comment by donovanmuller** [comment]
For example, using:

```yaml
apiVersion: v1
kind: Template
metadata:
  name: "spring-cloud-dataflow-server-openshift-ephemeral-kafka"
  annotations:
    openshift.io/display-name: "Spring Cloud Data Flow Server for OpenShift with ephemeral datasources and Kafka Template"
    description: |-
      A Spring Cloud Data Flow Server for OpenShift template.
      This template deploys the Data Flow Server, an ephemeral MySQL container, an ephemeral Redis container and a Kafka environment.
      These resources sare configured by means of the ConfigMap.
    iconClass: "icon-spring"
    tags: "integration,spring-cloud"
...
```

<img width="750" alt="screen shot 2017-02-19 at 4 34 30 pm" src="https://cloud.githubusercontent.com/assets/1175891/23103270/6f01432e-f6c1-11e6-8c17-a63711786cb6.png">
